# Generated by Django 4.1.2 on 2023-01-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='ユーザーネーム', max_length=255, verbose_name='user')),
                ('passward', models.CharField(default='パスワード', max_length=6, verbose_name='pass')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='user',
            field=models.CharField(default='ユーザーネーム', max_length=255, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='topics',
            name='user',
            field=models.CharField(default='ユーザーネーム', max_length=255, verbose_name='user'),
        ),
    ]
